name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    workspace:
      clean: outputs
    
    pool:
        name: Hosted VS2017
        demands: azureps

    steps:
    - script: echo Testing on Windows!