name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    workspace:
      clean: outputs
    
    pool:
      name: Hosted VS2017
      demands: azureps

    steps:
    - task: AzurePowerShell@3
      displayName: 'Azure PowerShell script: azuredeploy.ps1'
      inputs:
        azureSubscription: 'PAT Production'
        ScriptPath: ps/azuredeploy.ps1
        ScriptArguments: '-dtap development -sourcePath $(Build.Repository.LocalPath) -SourceVersion $(Build.BuildNumber) -WhatIf $true'
        preferredAzurePowerShellVersion: 6.7.0