name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

variables:
  skipComponentGovernanceDetection: true

stages:
- stage: Build
  jobs:
  - job: BuildJob
    
    pool:
      name: Hosted VS2017
      demands: azureps

    steps:
#    - task: AzurePowerShell@3
#      displayName: 'Azure PowerShell script: azuredeploy.ps1'
#      inputs:
#        azureSubscription: 'PAT Production'
#        ScriptPath: ps/azuredeploy.ps1
#        ScriptArguments: '-dtap development -sourcePath $(Build.Repository.LocalPath) -SourceVersion $(Build.BuildNumber) -WhatIf $true'
#        preferredAzurePowerShellVersion: 6.7.0
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\resource-groups'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)\resource-groups'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\ps'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)\ps'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop-preview'

- stage: Deploy
  jobs:
  - job: DeployJob

    pool:
      name: Hosted VS2017
      demands: azureps

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'drop-preview'

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**'
        downloadPath: '$(System.DefaultWorkingDirectory)/_pat-sql_db_lab'

    - task: AzurePowerShell@4
      displayName: 'Azure PowerShell script: inline test'
      inputs:
        azureSubscription: 'PAT Production'
        inline: 'Get-Location'
        preferredAzurePowerShellVersion: 5.1.1

    - task: AzurePowerShell@3
      displayName: 'Azure PowerShell script: azuredeploy.ps1'
      inputs:
        azureSubscription: 'PAT Production'
        ScriptPath: '$(System.DefaultWorkingDirectory)/_pat-sql-db-lab/drop/ps/azuredeploy.ps1'
        ScriptArguments: '-dtap development -sourcePath $(System.DefaultWorkingDirectory)\_pat-sql-db-lab\drop -SourceVersion $(Build.SourceVersion) -WhatIf $false'
        preferredAzurePowerShellVersion: 6.7.0