name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

stages:
- stage: pat-sql-db-lab_build
#    displayName: pat-sql-db-lab Build
    jobs:
    - job: Job1
        workspace:
            clean: outputs



        